const $ = (s, root = document) => root.querySelector(s);
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const now = () => new Date().toISOString();
const esc = (value = "") => String(value).replace(/[&<>"']/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" }[c]));

const storage = {
  key: "aria-os-v1",
  load() { try { return JSON.parse(localStorage.getItem(this.key)); } catch { return null; } },
  save(data) { localStorage.setItem(this.key, JSON.stringify(data)); },
  export() { return JSON.stringify({ schema: 1, exportedAt: now(), data: state }, null, 2); },
};
const initial = {
  profile:{ name:"Andressa", relationshipStart:"2024-05-05", theme:"midnight" },
  tasks:[{id:uid(),title:"Finalizar o plano de hoje",priority:"alta",due:"Hoje",done:false,tags:["foco"],createdAt:now()},{id:uid(),title:"Enviar uma mensagem especial",priority:"média",due:"Hoje",done:false,tags:["sintonia"],createdAt:now()}],
  habits:[{id:uid(),title:"Água com presença",streak:4,done:false},{id:uid(),title:"Pausa gentil",streak:8,done:true}],
  diary:[], memories:[], routines:[{id:uid(),title:"Ritual de desacelerar",time:"21:30",done:false}], medications:[], goals:[{id:uid(),title:"Cuidar do nosso ritmo",progress:62}], finances:[], gallery:[], notifications:[{id:uid(),text:"Seu espaço está pronto para receber novas memórias.",read:false,type:"Sistema"}], timeline:[{id:uid(),type:"system",title:"Aria.OS despertou",detail:"Seu ecossistema local está ativo.",at:now()}], chats:[{id:uid(),role:"aria",text:"Oi, Andressa. Estou aqui para tornar o seu agora um pouco mais leve. O que você precisa?"}], usage:{}, settings:{ widgets:["priority","metrics","timeline","quick"] }
};
let state = storage.load() || initial;
const events = new EventTarget();
function persist(){storage.save(state); events.dispatchEvent(new Event("change"));}
function addTimeline(title, detail, type="system"){state.timeline.unshift({id:uid(),title,detail,type,at:now()}); state.timeline=state.timeline.slice(0,80)}
function notify(text,type="Aria"){state.notifications.unshift({id:uid(),text,type,read:false}); persist();}
function route(){return location.hash.slice(1) || "home"}
function go(to){location.hash=to}
const nav = [{id:"home",icon:"⌂",label:"Seu agora"},{id:"neural",icon:"◈",label:"Neural Fabric"},{id:"tasks",icon:"✓",label:"Tarefas"},{id:"diary",icon:"◫",label:"Diário"},{id:"routine",icon:"◷",label:"Rotina"},{id:"princess",icon:"♡",label:"Modo Princesa"},{id:"aria",icon:"✦",label:"Aria Copilot"},{id:"frequency",icon:"∞",label:"Nossa Frequência"},{id:"finance",icon:"◐",label:"Finanças"},{id:"gallery",icon:"▧",label:"Galeria"},{id:"admin",icon:"⚙",label:"Admin Core"}];
function renderNav(){ $("#sidebar-nav").innerHTML = nav.map(n=>`<button data-route="${n.id}" class="${route()===n.id?"active":""}"><span>${n.icon}</span><span>${n.label}</span></button>`).join("") }
function actionButton(label, action, cls="primary"){return `<button class="${cls}" data-action="${action}">${label}</button>`}
function stat(value,label,detail){return `<article class="panel metric"><span>${label}</span><div class="metric-value">${value}</div><small>${detail}</small></article>`}
function list(items, kind, emptyText){if(!items.length)return `<div class="empty">${emptyText}</div>`;return `<div class="panel list-card">${items.map(item=>`<div class="list-row"><span class="list-row-icon">${kind.icon}</span><div class="list-row-content ${item.done?"done":""}"><b>${esc(item.title||item.name)}</b><small>${esc(item.due||item.time||item.content||item.category||"")}</small></div>${kind.toggle?`<button class="secondary" data-toggle="${kind.name}" data-id="${item.id}">${item.done?"Reabrir":"Concluir"}</button>`:""}</div>`).join("")}</div>`}
function home(){let pending=state.tasks.filter(t=>!t.done); let completed=state.habits.filter(h=>h.done).length;return `<div class="hero"><div><span class="eyebrow">CONTEXTO ATUAL · ${new Date().toLocaleDateString("pt-BR",{weekday:"long"}).toUpperCase()}</span><h2>Boa ${hourGreeting()}, ${esc(state.profile.name)}.</h2><p>${pending.length?`Existem ${pending.length} pontos pedindo sua atenção — sem perder a delicadeza do seu ritmo.`:"Seu ecossistema está tranquilo. Há espaço para criar, respirar e estar presente."}</p></div><div class="live-indicator"><i></i> ARIA LOCAL-FIRST · ONLINE</div></div><div class="cockpit"><article class="panel priority"><span class="eyebrow">PRIORIDADE GENTIL</span><h3>${pending[0]?esc(pending[0].title):"Seu espaço está livre para uma nova intenção."}</h3><p>${pending[0]?`Uma tarefa ${pending[0].priority} para hoje. Comece pequeno; o próximo passo já é movimento.`:"Escolha uma intenção e conecte-a à sua história."}</p><div class="priority-actions">${pending[0]?actionButton("Concluir agora","complete-priority"):actionButton("Criar intenção","new-task")}${actionButton("Abrir foco","pomodoro","secondary")}</div></article><div class="metrics">${stat(pending.length,"TAREFAS ABERTAS",pending.length?"para o seu agora":"tudo em ordem")}${stat(`${completed}/${state.habits.length}`,"HÁBITOS HOJE",completed?"ritmo presente":"comece com leveza")}${stat(state.routines.filter(r=>r.done).length,"ROTINAS",state.routines.length?"próxima às "+state.routines[0].time:"nenhuma programada")}${stat("62%","SINTONIA","em harmonia")}</div></div><div class="wide-grid"><article class="panel section-card"><div class="section-heading"><h3>Neural Timeline</h3><button class="text-button" data-route="neural">Ver conexões →</button></div><div class="timeline">${state.timeline.slice(0,5).map(t=>`<div class="timeline-item"><time>${new Date(t.at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time><span class="timeline-dot"></span><div><b>${esc(t.title)}</b><p>${esc(t.detail)}</p></div></div>`).join("")}</div></article><article class="panel section-card"><div class="section-heading"><h3>Ações rápidas</h3><span class="eyebrow">COMMAND-FIRST</span></div><div class="quick-actions">${[["＋","Tarefa","new-task"],["◫","Diário","new-diary"],["◈","Memória","new-memory"],["◷","Foco","pomodoro"]].map(x=>`<button class="quick-action" data-action="${x[2]}"><span>${x[0]}</span><b>${x[1]}</b><small>criar agora</small></button>`).join("")}</div></article></div>`}
function hourGreeting(){let h=new Date().getHours();return h<12?"dia":h<18?"tarde":"noite"}
function tasks(){return page("Tarefas","Transforme intenções em passos pequenos e conectados.","＋ Nova tarefa","new-task",list(state.tasks,{name:"task",icon:"✓",toggle:true},"Ainda não há tarefas. Crie sua primeira intenção."))}
function diary(){return page("Diário de Sintonia","Um espaço privado para registrar o que importa e reencontrar padrões.","＋ Novo registro","new-diary",list(state.diary,{icon:"◫"},"Ainda não há registros. Sua próxima memória pode começar aqui."))}
function routine(){return page("Rotina & medicamentos","Organize lembretes com autonomia — sem recomendações de tratamento.","＋ Adicionar rotina","new-routine",`${list(state.routines,{name:"routine",icon:"◷",toggle:true},"Nenhuma rotina criada ainda.")}<div class="spaced">${list(state.medications,{icon:"✚"},"Nenhum medicamento registrado. Seus dados ficam somente neste dispositivo.")}</div>`)}
function neural(){let nodes=[...state.tasks.map(x=>({title:x.title,type:"Tarefa"})),...state.diary.map(x=>({title:x.title,type:"Diário"})),...state.memories.map(x=>({title:x.title,type:"Memória"}))];return page("Neural Fabric","Relações, contexto e memória em um grafo pessoal local.","＋ Conectar memória","new-memory",`<article class="panel neural-map"><svg viewBox="0 0 1000 500" preserveAspectRatio="none"><path d="M500 250 L180 130 M500 250 L820 130 M500 250 L180 390 M500 250 L820 390" stroke="currentColor" fill="none"/></svg><div class="node center">ARIA<br>FABRIC</div><div class="node">Tarefas<br>${state.tasks.length} nós</div><div class="node">Diário<br>${state.diary.length} nós</div><div class="node">Hábitos<br>${state.habits.length} nós</div><div class="node">Memórias<br>${state.memories.length} nós</div></article><article class="panel section-card"><div class="section-heading"><h3>Backlinks recentes</h3><span class="eyebrow">${nodes.length} NÓS INDEXADOS</span></div>${nodes.length?nodes.slice(0,6).map(n=>`<div class="list-row"><span class="list-row-icon">◈</span><div class="list-row-content"><b>${esc(n.title)}</b><small>${n.type} · disponível na busca global</small></div></div>`).join(""):"<div class=empty>Comece criando uma tarefa, memória ou registro para ativar sua rede.</div>"}</article>`) }
function aria(){return page("Aria Copilot","Uma presença local baseada em intenções. Sem diagnóstico e sem enviar seus dados para servidores.","Limpar conversa","clear-chat",`<article class="panel chat"><div id="messages" class="messages">${state.chats.map(m=>`<div class="message ${m.role}">${esc(m.text)}</div>`).join("")}</div><form class="chat-form" id="chat-form"><input id="chat-input" aria-label="Mensagem para Aria" placeholder="Conte o que está sentindo ou quer fazer…" autocomplete="off"><button class="primary">Enviar</button></form></article>`)}
function princess(){return page("Modo Princesa","Uma pausa delicada para voltar ao corpo e ao seu ritmo.","Tocar 432 Hz","tone",`<article class="panel princess"><span class="eyebrow">RESPIRAÇÃO DO BALÃOZINHO</span><div class="balloon"></div><h2>Respire com calma.</h2><p>Inspire enquanto o balão cresce. Expire enquanto ele retorna. Ajuste seu ritmo, sem pressa.</p><div class="breath-controls"><button data-breath="4-4">4 · 4</button><button data-breath="4-6">4 · 6</button><button data-breath="4-7-8">4 · 7 · 8</button><button data-action="tone">Tom 432 Hz</button></div><small class="tone-note">O tom é um recurso sonoro de ambiente, não uma terapia ou orientação médica.</small></article>`) }
function frequency(){return page("Nossa Frequência","Uma linha do tempo viva para celebrar o que vocês constroem juntos.","Adicionar marco","new-memory",`<article class="panel frequency"><div><span class="eyebrow">DESDE 05 · 05 · 2024</span><h2>Nosso tempo é casa.</h2><p>cada segundo também é uma memória em construção</p><div class="counter" id="counter"></div></div></article>`)}
function finance(){let total=state.finances.reduce((a,x)=>a+(x.type==="income"?x.amount:-x.amount),0);return page("Finanças locais","Clareza financeira sem sair do seu dispositivo.","＋ Novo lançamento","new-finance",`<div class="metrics" class="metrics finance-metrics">${stat("R$ "+total.toFixed(2).replace(".",","),"SALDO LOCAL","dados privados")}${stat(state.finances.filter(x=>x.type==="income").length,"RECEITAS","lançamentos")}${stat(state.finances.filter(x=>x.type!=="income").length,"DESPESAS","lançamentos")}</div><div class="spaced">${list(state.finances,{icon:"◐"},"Nenhum lançamento ainda. Crie o primeiro para começar a visualizar seu fluxo.")}</div>`)}
function gallery(){return page("Galeria local","Imagens guardadas no navegador, vinculáveis às suas memórias.","＋ Adicionar imagem","upload",`<article class="panel section-card"><div class="empty">Sua galeria está aguardando uma lembrança. As imagens permanecem neste dispositivo.</div></article>`)}
function admin(){let capabilities=[["Storage",true],["IndexedDB","indexedDB" in window],["Service Worker","serviceWorker" in navigator],["Notifications","Notification" in window],["Web Audio","AudioContext" in window||"webkitAudioContext" in window],["Web Crypto","crypto" in window],["BroadcastChannel","BroadcastChannel" in window]];return page("Admin Core","Diagnóstico, backup e governança local. Este painel não simula segurança de servidor.","Exportar backup","export",`<article class="panel section-card"><div class="section-heading"><h3>Diagnóstico do ambiente</h3><button class="text-button" data-action="import">Importar backup</button></div><div class="diagnostic">${capabilities.map(([name,ok])=>`<div class="panel"><b>${name}</b><small class="${ok?"status-supported":"status-unsupported"}">${ok?"SUPPORTED":"UNSUPPORTED"}</small></div>`).join("")}</div></article><article class="panel section-card"><h3>Privacidade e dados</h3><p class="privacy-copy">Aria.OS funciona somente no navegador. O backup é um arquivo JSON sob seu controle; os dados não são enviados a um backend.</p></article>`)}
function page(title,description,button,action,content){return `<div class="module-page"><div class="page-lead"><div><span class="eyebrow">MÓDULO ARIA.OS</span><h2>${title}</h2><p>${description}</p></div>${actionButton(button,action)}</div>${content}</div>`}
const views={home,tasks,diary,routine,neural,aria,princess,frequency,finance,gallery,admin};
function render(){let r=route(); if(!views[r])r="home"; $("#view").innerHTML=views[r](); $("#page-title").textContent=nav.find(n=>n.id===r)?.label||"Seu agora"; $("#page-eyebrow").textContent=r==="home"?"NEURAL COCKPIT":"ARIA.OS MODULE"; renderNav(); if(r==="frequency")startCounter(); if(r==="aria")$("#messages")?.scrollTo(0,9999);}
function modal(title, body){$("#layer").innerHTML=`<div class="modal-wrap" data-action="dismiss"><section class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-head"><h2>${esc(title)}</h2><button class="close" data-action="dismiss" aria-label="Fechar">×</button></div>${body}</section></div>`; $("#layer input, #layer textarea")?.focus()}
function form(type){let configs={"new-task":["Nova tarefa",`<label class=field>Título<input name=title required placeholder="Ex.: Estudar amanhã"></label><label class=field>Prioridade<select name=priority><option>alta</option><option selected>média</option><option>baixa</option></select></label><label class="field full">Prazo<input name=due placeholder="Hoje, amanhã…"></label>`],"new-diary":["Novo registro",`<label class="field full">Título<input name=title required placeholder="Dê um nome ao momento"></label><label class="field full">Como foi?<textarea name=content required placeholder="Escreva sem filtro…"></textarea></label>`],"new-memory":["Nova memória",`<label class="field full">Título<input name=title required placeholder="Uma memória para conectar"></label><label class="field full">Detalhe<textarea name=content placeholder="O que você quer guardar?"></textarea></label>`],"new-routine":["Nova rotina",`<label class=field>Nome<input name=title required placeholder="Ritual da noite"></label><label class=field>Horário<input name=time type=time required value="21:30"></label>`],"new-finance":["Novo lançamento",`<label class=field>Descrição<input name=title required></label><label class=field>Valor (R$)<input name=amount type=number step=.01 required></label><label class="field full">Tipo<select name=type><option value=expense>Despesa</option><option value=income>Receita</option></select></label>`]};let [title,fields]=configs[type];modal(title,`<form id="entity-form" class="form-grid" data-form="${type}">${fields}<div class="form-actions full">${actionButton("Cancelar","dismiss","secondary")}<button class="primary">Salvar</button></div></form>`)}
function saveForm(form){let data=Object.fromEntries(new FormData(form));let type=form.dataset.form;let key={"new-task":"tasks","new-diary":"diary","new-memory":"memories","new-routine":"routines","new-finance":"finances"}[type];let entry={...data,id:uid(),createdAt:now(),done:false};if(key==="finances")entry.amount=Number(entry.amount); if(key==="habits")entry.streak=0; state[key].unshift(entry);addTimeline(type==="new-diary"?"Novo registro no Diário":type==="new-memory"?"Nova memória conectada":type==="new-task"?"Nova tarefa criada":"Novo item registrado",entry.title,"created");persist();$("#layer").innerHTML="";toast("Salvo no seu ecossistema.");render()}
function command(){let all=[...nav.map(x=>({icon:x.icon,title:"Abrir "+x.label,run:()=>go(x.id),shortcut:""})),{icon:"＋",title:"Nova tarefa",run:()=>form("new-task"),shortcut:"T"},{icon:"◫",title:"Novo registro no Diário",run:()=>form("new-diary")},{icon:"◈",title:"Nova memória",run:()=>form("new-memory")},{icon:"◷",title:"Iniciar Pomodoro",run:pomodoro},{icon:"♡",title:"Respirar",run:()=>go("princess")}];modal("Command Palette",`<input class="command-input" id="command-search" placeholder="Busque, navegue ou escreva “criar tarefa estudar amanhã”" autofocus><div class="command-list" id="command-list"></div>`);const input=$("#command-search"), draw=()=>{let q=input.value.toLowerCase();let results=all.filter(c=>c.title.toLowerCase().includes(q));if(q.startsWith("criar tarefa "))results=[{icon:"＋",title:`Criar tarefa: ${input.value.slice(14)}`,run:()=>{state.tasks.unshift({id:uid(),title:input.value.slice(14),priority:"média",due:"",done:false,createdAt:now()});addTimeline("Nova tarefa criada",input.value.slice(14));persist();$("#layer").innerHTML="";render();toast("Tarefa criada.")}}];$("#command-list").innerHTML=results.map((r,i)=>`<button class="command-item" data-command="${i}"><span>${r.icon}</span><b>${esc(r.title)}</b><small>${r.shortcut}</small></button>`).join("")||"<div class=empty>Nada encontrado. Tente uma intenção diferente.</div>";$("#command-list").onclick=e=>{let i=e.target.closest("[data-command]")?.dataset.command;if(i!==undefined)results[i].run()}};input.oninput=draw;draw()}
function pomodoro(){go("home");toast("Foco iniciado por 25 minutos. Um passo por vez.");addTimeline("Pomodoro iniciado","25 minutos reservados para você.","focus");persist()}
function tone(){let Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx){toast("Áudio não disponível neste navegador.");return}let ctx=new Ctx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=432;gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.08,ctx.currentTime+.4);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+12);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+12);toast("Tom de ambiente iniciado por 12 segundos.")}
function toast(text){const t=document.createElement("div");t.className="toast";t.textContent=text;document.body.append(t);setTimeout(()=>t.remove(),3200)}
function startCounter(){let target=new Date(state.profile.relationshipStart+"T00:00:00");let tick=()=>{let d=Math.max(0,Date.now()-target),days=Math.floor(d/864e5),hours=Math.floor(d/36e5)%24,min=Math.floor(d/6e4)%60,sec=Math.floor(d/1e3)%60;let c=$("#counter");if(c)c.innerHTML=[[days,"DIAS"],[hours,"HORAS"],[min,"MIN"],[sec,"SEG"]].map(x=>`<div><b>${x[0]}</b><small>${x[1]}</small></div>`).join("")};tick();clearInterval(window.ariaCounter);window.ariaCounter=setInterval(tick,1000)}
function handle(e){let target=e.target.closest("[data-action],[data-route],[data-toggle]");if(!target)return;if(target.dataset.route){go(target.dataset.route);return}let a=target.dataset.action;if(target.dataset.toggle){let arr=target.dataset.toggle==="task"?state.tasks:state.routines;let item=arr.find(x=>x.id===target.dataset.id);item.done=!item.done;addTimeline(item.done?"Item concluído":"Item reaberto",item.title,target.dataset.toggle);persist();render();return}if(a==="command")command();else if(["new-task","new-diary","new-memory","new-routine","new-finance"].includes(a))form(a);else if(a==="dismiss")$("#layer").innerHTML="";else if(a==="quick-create")command();else if(a==="complete-priority"){let t=state.tasks.find(x=>!x.done);if(t){t.done=true;addTimeline("Tarefa concluída",t.title,"task");persist();render();toast("Feito — seu ecossistema reconheceu o passo.")}}else if(a==="pomodoro")pomodoro();else if(a==="tone")tone();else if(a==="clear-chat"){state.chats=state.chats.slice(0,1);persist();render()}else if(a==="export"){let blob=new Blob([storage.export()],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="aria-os-backup.json";link.click();URL.revokeObjectURL(link.href);toast("Backup exportado.")}else if(a==="import"){let input=document.createElement("input");input.type="file";input.accept="application/json";input.onchange=async()=>{try{let f=input.files[0],o=JSON.parse(await f.text());if(o.schema!==1||!o.data)throw Error();state=o.data;persist();render();toast("Backup restaurado.")}catch{toast("Esse backup não é compatível.")}};input.click()}else if(a==="notifications"){modal("Central de notificações",state.notifications.length?state.notifications.map(n=>`<div class="list-row"><span class="list-row-icon">◌</span><div class=list-row-content><b>${esc(n.type)}</b><small>${esc(n.text)}</small></div></div>`).join(""):"<div class=empty>Nada novo por aqui.</div>");state.notifications.forEach(n=>n.read=true);persist()}else if(a==="theme"){document.documentElement.classList.toggle("light");toast("Tema alternado.")}else if(a==="menu")command()}
document.addEventListener("click",handle);document.addEventListener("submit",e=>{if(e.target.id==="entity-form"){e.preventDefault();saveForm(e.target)}if(e.target.id==="chat-form"){e.preventDefault();let input=$("#chat-input"),text=input.value.trim();if(!text)return;state.chats.push({id:uid(),role:"user",text});let l=text.toLowerCase(),reply=l.includes("ansios")?"Vamos reduzir o ritmo juntas. Quer abrir o Modo Princesa e fazer uma respiração guiada?":l.includes("organizar")||l.includes("muita coisa")?`Você tem ${state.tasks.filter(t=>!t.done).length} tarefas abertas. Podemos escolher só a primeira agora.`:l.includes("escrever")?"Seu Diário está pronto para receber esse momento.": "Estou com você. Posso ajudar a transformar isso em uma tarefa, uma memória ou uma pequena pausa.";state.chats.push({id:uid(),role:"aria",text:reply});addTimeline("Conversa com Aria","Uma intenção foi acolhida.","aria");persist();render()}});document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();command()}if(e.key.toLowerCase()==="t"&&!e.metaKey&&!e.ctrlKey&&document.activeElement.tagName!=="INPUT"&&document.activeElement.tagName!=="TEXTAREA")form("new-task");if(e.key==="Escape")$("#layer").innerHTML=""});window.addEventListener("hashchange",render);events.addEventListener("change",()=>{let unread=state.notifications.filter(n=>!n.read).length;$("#notification-dot").style.display=unread?"block":"none"});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));setTimeout(()=>{$("#boot").remove();$("#app").hidden=false;render();events.dispatchEvent(new Event("change"))},500);
